#mybatis 사용시 필수
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.cr0mkw8s2iwu.ap-northeast-2.rds.amazonaws.com:3306/library_db
    username: aws
    password: 1q2w3e4r!!

  mail:
    host: smtp.gmail.com
    port: 465
    username: opqwer3729@gmail.com
    address: opqwer3729@gmail.com
    password: qjakhmkpdiampcwy
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com


jwt:
    secret: RJE5qRjmbo+LDagujzt36VdlR7Uq2jdtbJQE0+iZ3dy9qD6EAKc/7nQDW/oUb0Rn


